name: CIBW CUDA

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: CUDA ${{ matrix.cuda-version }} wheels on ${{ matrix.target.arch }}
    runs-on: ${{ matrix.target.runner }}
    strategy:
      fail-fast: false
      matrix:
        # The CUDA Toolkit lives inside the custom manylinux images below, so
        # any runner works. See the list of available images at
        # https://github.com/pypa/cibuildwheel/pull/2896
        manylinux-base: [manylinux_2_28]
        cuda-version: [12_9, 13_1]
        target:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v6

    - uses: pypa/cibuildwheel@v3.4
      env:
        CIBW_BUILD: cp312-manylinux_${{ matrix.target.arch }}
        CIBW_MANYLINUX_X86_64_IMAGE: >-
          quay.io/manylinux_cuda/${{ matrix.manylinux-base }}_x86_64_cuda${{ matrix.cuda-version }}:latest
        CIBW_MANYLINUX_AARCH64_IMAGE: >-
          quay.io/manylinux_cuda/${{ matrix.manylinux-base }}_aarch64_cuda${{ matrix.cuda-version }}:latest

    - uses: actions/upload-artifact@v7
      with:
        name: cibw-cuda-${{ matrix.manylinux-base }}-cuda${{ matrix.cuda-version }}-${{ matrix.target.arch }}
        path: wheelhouse/*.whl
